### ISSUE TITLE
utils.js:37 Error: Returned error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/ico-wizard#399]
### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0xe394E2260b012A1A284c8526A3887c786BbE08D3&networkID=1

### Do you have screenshots showing the problem?

![image](https://user-images.githubusercontent.com/424628/33908023-12f96a2a-df55-11e7-8e8f-9b7d11962291.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

```
attach to crowdsale contract
utils.js:37 Error: Returned error: Unexpected token < in JSON at position 0
    at Object.ErrorResponse (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1388842)
    at https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1506550
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4120:13
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1336:9
From previous event:
    at i.h [as _captureStackTrace] (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1420387)
    at i._resolveFromExecutor (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1453642)
    at new i (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1446151)
    at o (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:524759)
    at n (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:239719)
    at Object.d._executeMethod (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1801944)
    at i (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:337796)
    at Object.callback (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:337650)
    at o (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:239955)
    at https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1506594
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
```
---

**Comment by fernandomg** [comment]
I was just checking this issue. Could reproduce it twice (just refreshing). But now I'm not being able to.

Also tested it in incognito mode, and no bugs anymore.

I'll review it again in a little while.

**Comment by fvictorio** [comment]
Fow what it's worth, this hapens when some contract in `public/contracts` is missing. But it's weird, because the app shouldn't start until of them are generated (or not start at all, if there was an error generating one of them).

**Comment by igorbarinov** [comment]
as far as I understood there was a problem with Netlify hosting and it didn't serve some content
may be we need some checks to get the app loaded before proceeding?

**Comment by fvictorio** [comment]
I agree with the idea, but I don't know what can we do that we are not doing now (chaining the contract creation and the start of the app with `&&`, so that it doesn't start if some contract fails). It seems to me that if the server has a problem serving content, there isn't much we can do about it.

For the time being, I'd close that issue and see if it happens again soon. If it does, we can discuss some approach to handling it.

**Comment by igorbarinov** [comment]
Thanks, I thought that we can get something about this exception, e.g. show a Sweet Alert that not all component was loaded "Something went wrong" style of message 

![image](https://user-images.githubusercontent.com/424628/33943033-d6fc1bb2-dfe5-11e7-8b89-ec4a8a805f96.png)

**Comment by fvictorio** [comment]
That seems reasonable. We should just add an error handler when fetching the contracts, right now it must be ignoring the 404s.
